service:
    hostname:
      discovery: localhost
      auth: localhost
      mysql: ${MYSQL_HOST:localhost}
      ui: localhost


security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8900/auth/user

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  jpa:
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddlAuto: update
      generate-ddl: true
      show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopprovip
    username: root
    password: ENC(rbOuS/eud6AztC1N0R4FDg==)
  mail:
    host: smtp.gmail.com
    username: duc.trantrung99@gmail.com
    password: ENC(O55yp9uj/S7myBJKQJZh1jwosoyyY2s+HUscOxVaozc=)
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8901

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


ui:
  url: http://localhost:3000

passwordResetTokenValidityHours: 24
