spring:
  application:
  name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/shopprovip
    username: root
    password: ENC(rbOuS/eud6AztC1N0R4FDg==)
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8000
security:
  oauth2:
    client:
      clientId: user-service
      clientSecret: user-service
      accessTokenUri: http://localhost:8762/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:8762/auth/user

discovery:
   hostname: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring-doc:
  swagger-ui:
    path=/swagger-ui-custom:
      html:

    operationsSorter=method: